language: node_js
node_js:
 - "node"
env:
 - PLATFORM_SERVICE=core/jazz_codeq
 - PLATFORM_SERVICE=core/jazz_create-serverless-service
 - PLATFORM_SERVICE=core/jazz_delete-serverless-service
 - PLATFORM_SERVICE=core/jazz_deployments
 - PLATFORM_SERVICE=core/jazz_deployments-event-handler
 - PLATFORM_SERVICE=core/jazz_environments
 - PLATFORM_SERVICE=core/jazz_environment-event-handler
 - PLATFORM_SERVICE=core/jazz_events
 - PLATFORM_SERVICE=core/jazz_is-service-available
 - PLATFORM_SERVICE=core/jazz_login
 - PLATFORM_SERVICE=core/jazz_logout 
 - PLATFORM_SERVICE=core/jazz_scm-webhook
 - PLATFORM_SERVICE=core/jazz_services
 - PLATFORM_SERVICE=core/jazz_services-handler

before_script:
  - npm prune
  
script: cd $PLATFORM_SERVICE && npm install && npm test
