language: node_js
node_js:
 - "node"
env:
 - PLATFORM_SERVICE=jazz_login
 - PLATFORM_SERVICE=jazz_logout
 - PLATFORM_SERVICE=jazz_create-serverless-service
 - PLATFORM_SERVICE=jazz_delete-serverless-service
 - PLATFORM_SERVICE=jazz_is-service-available
 - PLATFORM_SERVICE=jazz_services
 - PLATFORM_SERVICE=jazz_logs
 - PLATFORM_SERVICE=jazz_environments
 - PLATFORM_SERVICE=jazz_environment-event-handler

before_script:
  - npm prune
  
script: cd $PLATFORM_SERVICE && npm install && npm test
